[build]
target = "wasm32-unknown-unknown"
rustflags = [
  "-C",
  "target-cpu=bleeding-edge",
  "-C",
  "target-feature=+bulk-memory,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,+sign-ext,+simd128",
  "--cfg",
  "getrandom_backend=\"custom\"",
]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
debug-assertions = false
overflow-checks = false
